# coding: utf-8

"""
    Text Classification Service

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import zimp_clf_client
from zimp_clf_client.api.training_api import TrainingApi  # noqa: E501
from zimp_clf_client.rest import ApiException


class TestTrainingApi(unittest.TestCase):
    """TrainingApi unit test stubs"""

    def setUp(self):
        self.api = zimp_clf_client.api.training_api.TrainingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clf_train_post(self):
        """Test case for clf_train_post

        Trains a model using a csv file with ',' delimiters and the column headers 'text', 'target'  # noqa: E501
        """
        pass

    def test_clf_training_status_get(self):
        """Test case for clf_training_status_get

        Checks if a trained model is available (and fully trained)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
